# Generated by Django 3.1.4 on 2020-12-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='map',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('lat', models.DecimalField(db_column='lat', decimal_places=10, max_digits=65)),
                ('lng', models.FloatField(db_column='lng')),
            ],
            options={
                'db_table': 'map',
                'managed': False,
            },
        ),
    ]
