# Generated by Django 3.1.4 on 2020-12-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.TextField(db_column='title')),
                ('content', models.TextField(db_column='content')),
            ],
            options={
                'db_table': 'Board',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='map',
            table='Map',
        ),
    ]
